name: 打包项目
on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  npm-build:
    name: ==== 执行 npm-build 工作流 ====
    runs-on: ubuntu-latest

    steps:
      - name: ==== 读取仓库内容 ====
        uses: actions/checkout@v4

      - name: ==== 安装依赖 和 打包 ====
        run: |
          yarn
          yarn run build

      - name: ==== 项目部署 ====
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: prod-pages
          folder: dist
