name: 构建镜像文件并推送docker hub
on:
  push:
    branches:
      - dev

jobs:
  npm-build:
    name: ==== 执行 npm-build 工作流 ====
    runs-on: ubuntu-latest

    steps:
      - name: ==== 读取仓库内容 ====
        uses: actions/checkout@v4

      - name: ==== 登录docker hub ====
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      - name: ==== 构建 推送docker hub ====
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: xiaohu1007/xiaohu-demo-vue:latest
