name: 构建镜像文件并推送docker hub
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: ==== 执行 npm-build 工作流 ====
    runs-on: ubuntu-latest

    steps:
      - name: ==== 读取仓库内容 ====
        uses: actions/checkout@v4
      - name: ==== 设置页面 ====
        id: pages
        uses: actions/configure-pages@v3
      - name: ==== 安装依赖 和 打包 ====
        run: |
          yarn
          yarn run build

      - name: ==== 项目部署 ====
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
