name: 构建镜像文件并推送docker hub
on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  npm-build:
    name: ==== 执行 npm-build 工作流 ====
    runs-on: ubuntu-latest

    steps:
      - name: ==== 读取仓库内容 ====
        uses: actions/checkout@v4

      - name: ==== 安装依赖 和 打包 ====
        run: |
          yarn
          yarn run build

      - name: ==== 项目部署 ====
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ==== 获取生成地址 ====
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: ==== 是生产环境 ====
        id: deployment
        uses: actions/deploy-pages@v4
